<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Config' => $baseDir . '/model/Config.class.php',
    'Retorno' => $baseDir . '/model/Retorno.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Sql' => $baseDir . '/model/Sql.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'Usuario' => $baseDir . '/model/Usuario.class.php',
);
