<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0d6c5ba1d166ace972e93ce06d9f3ef2
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Retorno' => __DIR__ . '/../..' . '/model/Retorno.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Sql' => __DIR__ . '/../..' . '/model/Sql.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
        'Usuario' => __DIR__ . '/../..' . '/model/Usuario.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0d6c5ba1d166ace972e93ce06d9f3ef2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0d6c5ba1d166ace972e93ce06d9f3ef2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0d6c5ba1d166ace972e93ce06d9f3ef2::$classMap;

        }, null, ClassLoader::class);
    }
}
